version: '3.8'

services:
  # Development configuration with hot reload
  sortedstorage-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sortedstorage-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PUBLIC_API_URL=http://localhost:8090
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - storage-network
    command: npm run dev -- --host

  # Solobase Backend in development mode
  solobase-dev:
    build:
      context: ../go/solobase
      dockerfile: Dockerfile
    container_name: solobase-dev
    ports:
      - "8090:8090"
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=file:./.data/solobase.db
      - DEFAULT_ADMIN_EMAIL=admin@sortedstorage.com
      - DEFAULT_ADMIN_PASSWORD=Test123456789!
      - STORAGE_TYPE=local
      - STORAGE_PATH=/data/storage
      - JWT_SECRET=dev-secret-key
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - DEBUG=true
    volumes:
      - ./dev-data:/data
      - ./dev-storage:/data/storage
      - ../go/solobase:/app
    networks:
      - storage-network
    command: go run .

networks:
  storage-network:
    driver: bridge