name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App to deploy (store, profile, cdn, docs, or all)'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - store
        - profile
        - cdn
        - docs
        - dashboard

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        app: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.app_name == 'all' && fromJson('["store", "profile", "cdn", "docs", "dashboard"]') || fromJson(format('["{0}"]', github.event.inputs.app_name))) || fromJson('["store", "profile", "cdn", "docs", "dashboard"]') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Deploy ${{ matrix.app }}
      run: |
        SERVICE_NAME="suppers-${{ matrix.app }}-staging"
        IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/suppers/${SERVICE_NAME}"
        
        # Build Docker image with app name
        docker build --build-arg APP_NAME=${{ matrix.app }} -t ${IMAGE_NAME} .
        
        # Push to Artifact Registry
        docker push ${IMAGE_NAME}
        
        # Deploy to Cloud Run
        gcloud run deploy ${SERVICE_NAME} \
          --image ${IMAGE_NAME} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars="ENVIRONMENT=staging"

    - name: Get service URL
      run: |
        SERVICE_NAME="suppers-${{ matrix.app }}-staging"
        URL=$(gcloud run services describe ${SERVICE_NAME} --region=${{ env.REGION }} --format='value(status.url)')
        echo "🚀 ${{ matrix.app }} deployed to: ${URL}"